version: '3'
services:
  server1:
    image: server1-image
    ports:
      - '8001:80'
  
  server2:
    image: server2-image
    ports:
      - '8002:80'
  
  server3:
    image: server3-image
    ports:
      - '8003:80'

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
    volumes:
      - redis-data:/data

  elb:
    image: nginx:stable-perl
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cache:/var/cache/nginx/requsts_cache
    depends_on:
      - server1
      - server2
      - server3
      - redis

volumes:
  redis-data:
    driver: local